-- Add missing columns to results table
ALTER TABLE public.results 
ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'academic',
ADD COLUMN IF NOT EXISTS year INTEGER NOT NULL DEFAULT EXTRACT(YEAR FROM NOW()),
ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT false;