// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhcaqiyusketrluyaitt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoY2FxaXl1c2tldHJsdXlhaXR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzQyOTYsImV4cCI6MjA3NDIxMDI5Nn0.2BmeLPzs-7Tvo3LUT4kMC7lhgHkb0fKxwdpANvpZt5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});