// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsvwzvbxyjgoqobxwyvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxzdnd6dmJ4eWpnb3FvYnh3eXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTE4ODgsImV4cCI6MjA3MzcyNzg4OH0.cWuolEVMGiGJGNnXGeQLy6hyZbK106UZvSVjtemITxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});