// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puxqofeymurxaxxedumf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1eHFvZmV5bXVyeGF4eGVkdW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzQ1NTksImV4cCI6MjA3NDIxMDU1OX0.S8pWQQedqjTkHo0zXqj87Da5AuPFSyfrKGvhfqCBVGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});